services:
  - type: web
    name: electricity-dashboard
    env: python
    region: oregon
    branch: main
    buildCommand: pip install --prefer-binary --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/Manikanta3920/Electricity_Dashboard
